test(runner): remove dispose method which causes error
Error: Trying to add a disposable to a DisposableStore that has already
been disposed of. The added object will be leaked!